<?php

namespace ContainerUJInU9e;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_LTYD6KrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.lTYD6Kr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.lTYD6Kr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\CountryController::delete' => ['privates', '.service_locator.cDqCNLH', 'get_ServiceLocator_CDqCNLHService', true],
            'App\\Controller\\CountryController::edit' => ['privates', '.service_locator.cDqCNLH', 'get_ServiceLocator_CDqCNLHService', true],
            'App\\Controller\\CountryController::index' => ['privates', '.service_locator.2goNfau', 'get_ServiceLocator_2goNfauService', true],
            'App\\Controller\\CountryController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CountryController::show' => ['privates', '.service_locator.CvcttIg', 'get_ServiceLocator_CvcttIgService', true],
            'App\\Controller\\MessageController::delete' => ['privates', '.service_locator.SJArFDd', 'get_ServiceLocator_SJArFDdService', true],
            'App\\Controller\\MessageController::edit' => ['privates', '.service_locator.SJArFDd', 'get_ServiceLocator_SJArFDdService', true],
            'App\\Controller\\MessageController::index' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\MessageController::new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MessageController::show' => ['privates', '.service_locator.O3A1vmO', 'get_ServiceLocator_O3A1vmOService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\CountryController:delete' => ['privates', '.service_locator.cDqCNLH', 'get_ServiceLocator_CDqCNLHService', true],
            'App\\Controller\\CountryController:edit' => ['privates', '.service_locator.cDqCNLH', 'get_ServiceLocator_CDqCNLHService', true],
            'App\\Controller\\CountryController:index' => ['privates', '.service_locator.2goNfau', 'get_ServiceLocator_2goNfauService', true],
            'App\\Controller\\CountryController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\CountryController:show' => ['privates', '.service_locator.CvcttIg', 'get_ServiceLocator_CvcttIgService', true],
            'App\\Controller\\MessageController:delete' => ['privates', '.service_locator.SJArFDd', 'get_ServiceLocator_SJArFDdService', true],
            'App\\Controller\\MessageController:edit' => ['privates', '.service_locator.SJArFDd', 'get_ServiceLocator_SJArFDdService', true],
            'App\\Controller\\MessageController:index' => ['privates', '.service_locator.sLkGFte', 'get_ServiceLocator_SLkGFteService', true],
            'App\\Controller\\MessageController:new' => ['privates', '.service_locator.CsMkqUa', 'get_ServiceLocator_CsMkqUaService', true],
            'App\\Controller\\MessageController:show' => ['privates', '.service_locator.O3A1vmO', 'get_ServiceLocator_O3A1vmOService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.oogCZpI', 'get_ServiceLocator_OogCZpIService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.rSTd.nA', 'get_ServiceLocator_RSTd_NAService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\CountryController::delete' => '?',
            'App\\Controller\\CountryController::edit' => '?',
            'App\\Controller\\CountryController::index' => '?',
            'App\\Controller\\CountryController::new' => '?',
            'App\\Controller\\CountryController::show' => '?',
            'App\\Controller\\MessageController::delete' => '?',
            'App\\Controller\\MessageController::edit' => '?',
            'App\\Controller\\MessageController::index' => '?',
            'App\\Controller\\MessageController::new' => '?',
            'App\\Controller\\MessageController::show' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\CountryController:delete' => '?',
            'App\\Controller\\CountryController:edit' => '?',
            'App\\Controller\\CountryController:index' => '?',
            'App\\Controller\\CountryController:new' => '?',
            'App\\Controller\\CountryController:show' => '?',
            'App\\Controller\\MessageController:delete' => '?',
            'App\\Controller\\MessageController:edit' => '?',
            'App\\Controller\\MessageController:index' => '?',
            'App\\Controller\\MessageController:new' => '?',
            'App\\Controller\\MessageController:show' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
