<?php

namespace ContainerWeI55Q8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CvcttIgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CvcttIg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CvcttIg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'country' => ['privates', '.errored..service_locator.CvcttIg.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.CvcttIg": it needs an instance of "App\\Entity\\Country" but this type has been excluded in "config/services.yaml".'],
        ], [
            'country' => 'App\\Entity\\Country',
        ]);
    }
}
