<?php

namespace ContainerWeI55Q8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CDqCNLHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.cDqCNLH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.cDqCNLH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'country' => ['privates', '.errored..service_locator.cDqCNLH.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.cDqCNLH": it needs an instance of "App\\Entity\\Country" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'country' => 'App\\Entity\\Country',
            'entityManager' => '?',
        ]);
    }
}
