<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEM6IfdL\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEM6IfdL/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEM6IfdL.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEM6IfdL\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEM6IfdL\App_KernelDevDebugContainer([
    'container.build_hash' => 'EM6IfdL',
    'container.build_id' => 'd04a1c88',
    'container.build_time' => 1702397501,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEM6IfdL');
