<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWeI55Q8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWeI55Q8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWeI55Q8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWeI55Q8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWeI55Q8\App_KernelDevDebugContainer([
    'container.build_hash' => 'WeI55Q8',
    'container.build_id' => '884704a7',
    'container.build_time' => 1701789900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWeI55Q8');
